### PR TITLE
Create wlan1 interface for wifi ap mode on phy0 in init.rc

### PR DESCRIPTION
**Pull request by zhaoye1**
iw phy phy0 interface add wlan1 type __ap

### CODE REVIEW

**Comment by zhaoye1** [comment]
@balajim001  please help me review the patch, and help me add Panda, Bharat B to review, thanks.

**Comment by zhaoye1** [comment]
@bpanda24 please help me review the patch

**Review by bpanda24 — APPROVED** [review]

**Review by maozhong1 — APPROVED** [review]

**Review by lchen43 — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Pull request merged**
