### PR TITLE
PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS build flag fix

### PR DESCRIPTION
**Pull request by AlamIntel**
Kernel check is failing for ivi,
since the API level is 33 but kernel used is 6.1.x
So, disabling kernel vintf check for now.
It will be enabled with API level upgrade.

Tests-Done: Build and boot android successfully.

Tracked-On: OAM-114732

### CODE REVIEW

**Review by tanujtekriwal — COMMENTED** [review]
Please write the description in the commit message after the commit header.

"Kernel check is failing for ivi since the API level is 33 but kernel used is 6.1.x
So disabling kernel vintf check for now. Will be enabled with API level upgrade"

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Pull request merged**
