### PR TITLE
Android/celadon

### PR DESCRIPTION
**Pull request by vdanix**

### CODE REVIEW

**Review by dyang23 — COMMENTED** [review]
The codec performace was calculated carefully by us, and pass CTS, but recently we also saw some failures, can you give more details like which platform, which release and the CiV configurations this patch apply to, and how about the CTS test result.

**Comment by vdanix** [comment]
@dyang23  we tested in ww15_01 vertical build all test are passing with this performance range changes for CML. we taken historical failed performance range data from ww01 to ww14_01 and given the fix .

**Review by sgnanase — APPROVED** [review]

**Comment by swaroopbalan** [comment]
PR created is wrong please follow guidelines

**Review by sgnanase — CHANGES_REQUESTED** [review]
Please submit changes directly, if required maintain bsp patches in vendor/intel/utils

**Pull request closed without merging**
