### PR TITLE
Adding location permission.

### PR DESCRIPTION
**Pull request by XuBing0**
System need location permission even it has no GPS hardware, it may use network to locate the position.

Test: run ats testHasLocationGpsFeatureFlag

Tracked-On: OAM-120814

### CODE REVIEW

**Review by dyang23 — APPROVED** [review]

**Review by vilasrk — COMMENTED** [review]
image

https://cs.android.com/android/platform/superproject/main/+/main:device/generic/car/common/car_core_hardware.xml;l=54?q=android.hardware.location.gps.xml

Comment says only device with GPS need location gps xml.

**Comment by XuBing0** [comment]
> image
> 
> https://cs.android.com/android/platform/superproject/main/+/main:device/generic/car/common/car_core_hardware.xml;l=54?q=android.hardware.location.gps.xml
> 
> Comment says only device with GPS need location gps xml.

check with ats test code, seems we need add the feature:
```
  @GasTest(requirement = "G-0-315")
  @Test
  public final void testHasLocationGpsFeatureFlag() {
    Assert.assertTrue("Device must declare 'android.hardware.location.gps' feature flag.", this.packageManager.hasSystemFeature("android.hardware.location.gps"));
  }
```

**Comment by yaoxinshi-intel** [comment]
From GAS, Automotive device implementations:
[G-0-45] MUST include a global positioning system (GPS) or global navigation satellite system (GNSS) receiver.
[G-0-315] MUST report the GPS/GNSS capability to Android through the android.hardware.location.gps feature flag.

**Review by zhy1030 — APPROVED** [review]

**Comment by XuBing0** [comment]
replace with https://github.com/intel-innersource/os.android.bsp.private-utils/pull/1429

**Pull request closed without merging**
