### PR TITLE
changing usb-gadget modules to static

### PR DESCRIPTION
**Pull request by RajaniRanjan**
dwc3 dynamic modules causing issues in recovery mode loading of usb gadget . hence moving from dynamic to static module for only dwc3 . 

Tracked-On: OAM-112957

### CODE REVIEW

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by rajucm2007 — APPROVED** [review]

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Please follow the commit message format
 
<short summary>
<blank line>
<Issue detailed>
<blank line>
<fix detailed>
<blank line>
Tracked-On:
Signed-off-by:
 
Note: Each line should be less than 72 characters

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
