### PR TITLE
Enable mei related kernel modules by default and enable i915 PXP in kernel config.

### PR DESCRIPTION
**Pull request by jsunintel**
Tracked-On: OAM-120417
Tracked-On: OAM-120422

### CODE REVIEW

**Comment by jsunintel** [comment]
@feijiang1 @HawieLong @manxiaoliang

**Comment by jsunintel** [comment]
[balajim001](https://github.com/balajim001), [bing8deng](https://github.com/bing8deng), [gkdeepa](https://github.com/gkdeepa), [JeevakaPrabu](https://github.com/JeevakaPrabu), [kaushlen](https://github.com/kaushlen), [lchen43](https://github.com/lchen43), [sgnanase](https://github.com/sgnanase), [shyjumon-n](https://github.com/shyjumon-n), [swaroopbalan](https://github.com/swaroopbalan), [yyao3](https://github.com/yyao3) and [zhy1030](https://github.com/zhy1030) Please kindly review and thanks a lot!

**Comment by jsunintel** [comment]
Found some issues during testing, please don't merge this yet.

**Review by feijiang1 — APPROVED** [review]
LGTM

**Pull request closed without merging**
