### PR TITLE
Fix media performance TCs

### PR DESCRIPTION
**Pull request by k-mochi**
performance range update for TGL

Tracked-On: OAM-99251
Signed-off-by: Kishan Mochi <kishan.mochi@intel.com>

### CODE REVIEW

**Comment by k-mochi** [comment]
@TianmiChen please review.

**Comment by dyang23** [comment]
please provide your test result.

**Comment by k-mochi** [comment]
attached to jira ticket please check @dyang23

**Review by dyang23 — APPROVED** [review]

**Comment by k-mochi** [comment]
@JeevakaPrabu please review.

**Review by TianmiChen — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
