### PR TITLE
Reduce logging after kernel boot-up

### PR DESCRIPTION
**Pull request by abhilashkesavan**
Tracked-On: OAM-71556
Signed-off-by: Madhusudhan S <madhusudhan.s@intel.com>

### CODE REVIEW

**Comment by abhilashkesavan** [comment]
@smadhusu pls review.

**Comment by tanminger** [comment]
When we debug, how to let the kernel output the detail log? Can use kernel command line option?

**Comment by smadhusu** [comment]
Yes, either you can use kernel command line option or you can do it from shell directly. 

Example: echo 7 > /proc/sys/kernel/printk

**Comment by tanminger** [comment]
If I use the kernel command line option of 'log_level=7', whether it will be replaced by 'echo 3> /proc/sys/kernel/printk' ?

**Comment by smadhusu** [comment]
No, it will be 7 only. I just meant there is an option to change the loglevel using command line. Eg: "echo <log_level_number> > /proc/sys/kernel/printk". 

Anyway with the PRs submitted, the loglevel is going to change only during the boot time( Here is the [PR](https://github.com/projectceladon/device-androidia/pull/148))..Once the kernel is up, we are changing the loglevel to default which is 3 (which is current PR).

**Comment by tanminger** [comment]
The default kernel log level is already defined to 3 by set the project-celadon/cel_apl/mixins.spec, line kernel: project-celadon(loglevel=3. It is used in device/intel/mixins/groups/kernel/project-celadon/BoardConfig.mk

**Comment by tanminger** [comment]
If this PR is a temporary patch, can you add the [DO NOT MERGE] in the title?
I will use https://github.com/projectceladon/hardware-intel-kernelflinger/pull/5 to add kernel command line option to debug the boot issue. It need the detail log of kernel.

**Comment by abhilashkesavan** [comment]
We would like to get this merged for the build, we will mark it as [REVERTME]. Is that OK ?

**Comment by abhilashkesavan** [comment]
I will share the detailed issue with you in a separate mail.

**Pull request merged**
