### PR TITLE
mapping system Input Method for Looking Glass Clients

### PR DESCRIPTION
**Pull request by RajaniRanjan**
input-port-association.xml file updating to match inputs.

Tracked-On: OAM-98032
Signed-off-by: RajaniRanjan <rajani.ranjan@intel.com>

### CODE REVIEW

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
May be a space between Rajani and Ranjan in Signed off?

**Review by balajim001 — APPROVED** [review]
LGTM

**Comment by RajaniRanjan** [comment]
> May be a space between Rajani and Ranjan in Signed off?
i think so it is correct. my signed of is RajaniRanjan

**Review by JeevakaPrabu — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
