### PR TITLE
config: enable ANDROID_AUTO_SUSPEND_BEHAVIOR

### PR DESCRIPTION
**Pull request by qizhangz**
Tracked-On: OAM-110029

### CODE REVIEW

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
As the diff patch https://github.com/projectceladon/vendor-intel-utils/pull/1889 is already under celadon_ivi, it should be ok to disable without defining a new kernel config. @kaushlen @rajucm2007 please comment

**Review by kaushlen — APPROVED** [review]

**Comment by qizhangz** [comment]
> As the diff patch [projectceladon/vendor-intel-utils#1889](https://github.com/projectceladon/vendor-intel-utils/pull/1889) is already under celadon_ivi, it should be ok to disable without defining a new kernel config. @kaushlen @rajucm2007 please comment

Do you mean it is no need to define a new kernel config?

**Comment by JeevakaPrabu** [comment]
> > As the diff patch [projectceladon/vendor-intel-utils#1889](https://github.com/projectceladon/vendor-intel-utils/pull/1889) is already under celadon_ivi, it should be ok to disable without defining a new kernel config. @kaushlen @rajucm2007 please comment
> 
> Do you mean it is no need to define a new kernel config?

Yes no need to add new kernel config

**Comment by qizhangz** [comment]
abandoned as the comments.

**Pull request closed without merging**
