### PR TITLE
Remove and update the graphics mixin group files

### PR DESCRIPTION
**Pull request by weiwushx**
Tracked-On: OAM-100951
Signed-off-by: wei, wushuangx <wushuangx.wei@intel.com>

### CODE REVIEW

**Review by feijiang1 — APPROVED** [review]
LGTM

**Comment by feijiang1** [comment]
@JeevakaPrabu  Please help review

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
- Tracked-On missing
- Provide detailed commit message. May be like
   -Removed not supported graphics mixin variants
   - Remove not used/needed board config flags in graphics auto mixin

**Comment by feijiang1** [comment]
@JeevakaPrabu Please help review again

**Review by feijiang1 — APPROVED** [review]

**Review by feijiang1 — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
