### PR TITLE
Battery: Patch to show correct battery percentage on the android screen

### PR DESCRIPTION
**Pull request by tanujtekriwal**
This patch enables to show correct battery percentage on the android screen.

Tracked-On: OAM-90977
Signed-off-by: Tanuj Tekriwal <tanuj.tekriwal@intel.com>

### CODE REVIEW

**Comment by tanujtekriwal** [comment]
> Can we make it dynamic please ?

can you please elaborate what you mean by dynamic?

**Comment by sgnanase** [comment]
Something like, if actual battery is present in HW then don't set above property.
If not, then set fake battery

**Comment by tanujtekriwal** [comment]
> Something like, if actual battery is present in HW then don't set above property.
> If not, then set fake battery. We dont want to different images for different HW.

Even if fake battery is enabled then it shows 100% battery status. With this removal actual battery if there will show proper value. So i think this shouldn't be an issue and no need to maintain 2 set of patches.

**Comment by tanujtekriwal** [comment]
> > Something like, if actual battery is present in HW then don't set above property.
> > If not, then set fake battery. We dont want to different images for different HW.
> 
> Even if fake battery is enabled then it shows 100% battery status. With this removal actual battery if there will show proper value. So i think this shouldn't be an issue and no need to maintain 2 set of patches.

And if real battery is not then also with this patch it shows 100% until battery is added and cic is restarted.

**Comment by sgnanase** [comment]
thanks. looks good to me (y)

**Pull request merged**
