### PR TITLE
Boot instability

### PR DESCRIPTION
**Pull request by JeevakaPrabu**

### CODE REVIEW

**Review by ceiba1985 — APPROVED** [review]

**Review by kaushlen — APPROVED** [review]

**Review by kaushlen — APPROVED** [review]

**Review by lchen43 — APPROVED** [review]
LGTM

**Review by lchen43 — APPROVED** [review]

**Review by Shao-Feng — APPROVED** [review]
LGTM

**Review by Shao-Feng — APPROVED** [review]
Thanks for removing the un-used property.

**Review by lchen43 — APPROVED** [review]

**Review by lchen43 — APPROVED** [review]

**Review by kaushlen — APPROVED** [review]

**Review by kaushlen — APPROVED** [review]

**Review by prabhatchand — APPROVED** [review]
Looks good to me

**Review by prabhatchand — APPROVED** [review]

**Review by prabhatchand — APPROVED** [review]

**Review by balajim001 — APPROVED** [review]
looks good to me

**Review by renchenglei — APPROVED** [review]

**Pull request merged**
