### PR TITLE
Experiment of Multi-User Multi-Display Car Feature.

### PR DESCRIPTION
**Pull request by ankithbti52509**
Porting all below PR chnages on MASTER branch-:
https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/22 https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/34 https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/85 https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/137 https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/51 https://github.com/intel-innersource/os.android.bsp.vendor-intel-utils/pull/69

Tracked-On: OAM-108917

### CODE REVIEW

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Please update the commit message detailing the issue and fix

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — APPROVED** [review]

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Pull request merged**
